### ISSUE TITLE
Unable to load D2R characters anymore

### ISSUE THREAD

**Issue by enders-blade** [dschu012/d2s-editor#37]
I haven't used this editor in a while.  I have a level 1 char that hasn't completed any quests, not wearing any gear, etc.  I use this char to load into the editor to modify items found on other characters.  I just tried loading him up and the editor does nothing.  No errors, no character, just sits there at the base screen.  I tried loading all of the other characters I have, none of them will load either.  If I roll a new char, that one will load.

**Comment by enders-blade** [comment]
Hmm, it seems to be item related.  I'm using the extracted MPQ in -direct -txt mode, but I haven't made any modifications to items at all.  But if I take an item from my shared stash, any weapon or armor it seems, and place it in the inventory of a character, that character can't load into the editor.  If I take one of my high level chars, strip all gear and items from them into the shared stash, the character will load up into the editor.

**Comment by remizca** [comment]
I'm using D2R ESP v1.7.1 mod and I've followed the instructions to make this work on the mod save files. I managed to create a character via this tool and adjust some stuff and also made an item for testing. I managed to play it on d2r but when i tried loading the save file again, it just wouldn't load. i can however create new character save files. i just can't open the save files anymore once i exit them. I will however try later the method used by the other commentor regarding moving the items from the character to the stash and try to load it up. I just can't right now because I'm at work.
