### ISSUE TITLE
Save Items

### ISSUE THREAD

**Issue by Momoz91** [dschu012/d2s-editor#68]
Hello !
Is it possible to add a function to save our items in .d2i format ?
Thanks

**Comment by BourbonCrow** [comment]
Not officially but i found a way to do it! and i can try to give you a step by step 
1. Right click the item you wanna save and click Share
2. The long string of text you get paste it [https://base64.guru/converter/decode/hex](https://base64.guru/converter/decode/hex) here don't change any settings and press Convert to Hex
3. copy the line it gave you into a blank text file that you named for example "Charm.d2i" then you need to save the file with Hexadecimal encoding else it wont work i use Sublime Text 4 build (4126).. Press File > Save with Encoding > Hexadecimal ....... (i bet you could do this with other text editors as well like Atom or Notepad++ but i don't know how in those cause i don't use them)
4. Done! You can now import your item

**Comment by BourbonCrow** [comment]
Just cause I'm nice i also downloaded Notepad++ since its a free alternative to figure out how to achieve the same 
step 1 and 2 are the same .. step3 is almost same... 
copy the line of text the website gave you into a empty file called lets say Charm.d2i then highlight all text using ctrl+a then press Plugins > MIME Tools > Base64 Decode and your file will look like it broke but don't worrie it did not now just save the file! and you should be able to load it up! @Momoz91
